AWSTemplateFormatVersion: 2010-09-09
Parameters:
  TableName:
    Description: Nome da tabela que sera criada
    Type: String
    Default: "Clientes"


AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "Nome"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "Nome"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: !Ref TableName
